---
name: "Jellyfin.Plugin.Ratings"
guid: "a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"
version: "1.0.0.0"
jellyfin_version: "10.11.0"
targetAbi: "10.11.0.0"
framework: "net8.0"
owner: "jellyfinratings"
overview: "Allow users to rate movies, series, and other media with a 1-10 star rating system"
description: >
  A comprehensive rating plugin for Jellyfin that allows users to rate any media item with a 1-10 star rating system.
  Features include:
  - Rate any media item (movies, series, episodes, music, etc.)
  - View average ratings and total rating count
  - See who rated what and their ratings on hover
  - Configure minimum/maximum rating values
  - Responsive star-based UI integrated into detail pages
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Ratings.dll"
changelog: >
  ## 1.0.0.0
  - Initial release
  - Star rating system (1-10)
  - User ratings with username display
  - Rating statistics and aggregation
  - Hover popup showing all user ratings
  - Configuration page
